// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // TODO: Reemplazar esto con la configuración real de tu proyecto Firebase
    // Ejecuta: flutterfire configure
    // Y reemplaza este archivo con el generado
    return const FirebaseOptions(
      apiKey: "temporal-api-key",
      appId: "1:1234567890:web:abcdef1234567890",
      messagingSenderId: "1234567890",
      projectId: "tattoobooker-340f8",
    );
  }
}